#! /bin/bash
# Wait until entrypoint fires
while ! [ -p /tmp/pipe ]; do sleep 5; done

if grep -wq "true" /etc/bootstrap/debugMode; then
    set -x
else
    exec &>> /tmp/pipe
fi


TEMPLATES_DIR="/templates"
WORKSPACE_DIR="/workspace"
ADDON="metrics-server"
CONFIG_FILE="/etc/bootstrap/config"
VERSION="$(cat /etc/bootstrap/version)"
FROM_VERSION="$(cat /etc/bootstrap/from_version)"
K8S_VERSION="$(cat /tools/k8s_version)"

make_cfg() {
    cp $WORKSPACE_DIR/metrics-server-template.yaml  $WORKSPACE_DIR/metrics-server.yaml

    openssl_out="$(openssl s_client -connect "$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" -showcerts < /dev/null)"
    python_script="
import re, sys
m = re.search('---\nCertificate chain\n(.*\n)*?---\nServer certificate', sys.argv[1])
print m.group(0)
"
    # python - forces python to accept the script from STDIN
    cert_chain="$(echo \"$python_script\" | python - \"$openssl_out\")"

    if [[ $cert_chain == *"/CN=kubernetes"* ]]; then
        # We have a signed cert
        echo "setting up signed cert mode"
        sed -i 's|@@@@MASTER_HOST_REQUIREMENT_STRING@@@@|\n        node-role.kubernetes.io/master: \"\"|g' $WORKSPACE_DIR/metrics-server.yaml
        sed -i 's|@@@@CA_PATH_OR_IGNORE@@@@|--kubelet-certificate-authority=/k8s-root-cert/ca.crt|g' $WORKSPACE_DIR/metrics-server.yaml
    else
        # We don't have a signed cert
        echo "setting up self-signed cert mode"
        sed -i 's|@@@@MASTER_HOST_REQUIREMENT_STRING@@@@||g' $WORKSPACE_DIR/metrics-server.yaml
        sed -i 's|@@@@CA_PATH_OR_IGNORE@@@@|--kubelet-insecure-tls|g' $WORKSPACE_DIR/metrics-server.yaml
    fi
    sed -i -e "s|^\(\s*image: \)|\1$bds_k8s_containerrepo|g" $WORKSPACE_DIR/metrics-server.yaml
}

# Utility functions to set error and initialize on the deployment configmap
set_deployment_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"initialize":"false","error":"false"}}'
}

set_deployment_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"initialize":"false","error":"true"}}'
}

clear_rollback() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"rollback":"false"}}'
}

set_reconfigure_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"reconfigure":"false","error":"false"}}'
}

set_reconfigure_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"reconfigure":"false","error":"true"}}'
}

set_upgrade_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"upgrade":"false","error":"false"}}'
}

set_upgrade_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"upgrade":"false","error":"true"}}'
}

# install related action for deploying the metrics-server
# bdconfig (bds_XXX_YYY) variables are available as environnment variables
# /etc/bootstrap/config files are available through configmap
install() {
    echo "$(date): Starting $ADDON install process"

    # copy from templates to workspace
    chmod 755 $WORKSPACE_DIR
    cp -a $TEMPLATES_DIR/* $WORKSPACE_DIR

    make_cfg
    kubectl create -f $WORKSPACE_DIR/metrics-server.yaml -n kube-system

    set_deployment_success
    return 0
}

reconfigure() {
    echo "$(date): Starting $ADDON reconfigure process"

    set_reconfigure_success
    return 0
}

# TEMPLATES_DIR will have the templates from new image and
# WORKSPACE_DIR will contain the existing modified ones.
# FROM_VERSION will contain the version that we are upgrading from
upgrade() {
    echo "$(date): Starting $ADDON upgrade process"

    set_upgrade_success
    return 0
}


rollback() {
    echo "$(date): Starting $ADDON rollback process"

    kubectl delete -f $WORKSPACE_DIR/metrics-server.yaml -n kube-system

    clear_rollback
    return 0
}

if [ "$1" == "--install" ]
then
    install
elif [ "$1" == "--rollback" ]
then
    rollback
elif [ "$1" == "--reconfigure" ]
then
    reconfigure
elif [ "$1" == "--upgrade" ]
then
    upgrade
else
    echo "invalid argument"
fi
