apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpecp-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpecp-agent
  template:
    metadata:
      labels:
        name: hpecp-agent
    spec:
      # This priorityClassName is only supported outside of kube-system in
      # K8s version 1.17.
      #priorityClassName: system-cluster-critical
      tolerations:
        - effect: NoSchedule
          operator: Exists
          key: node-role.kubernetes.io/master
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: hpecp-agent
          image: bluedata/hpecp-agent:@@@@VERSION@@@@
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hpecp-agent"
            - name: FSMOUNT_IMAGE_NAME
              value: @@@@FSMOUNT_DTAP_REPO@@@@/hpecp-fsmount:@@@@FSMOUNT_VERSION@@@@
            - name: DTAP_IMAGE_NAME
              value: @@@@FSMOUNT_DTAP_REPO@@@@/hpecp-dtap:@@@@DTAP_VERSION@@@@
            - name: KIALI_VERSION
              value: @@@@KIALI_VERSION@@@@
      serviceAccountName: hpecp-agent
