#! /bin/bash
# Let us wait for some time for entrypoint to fire
while ! [ -p /tmp/pipe ]; do sleep 5; done

if grep -wq "true" /etc/bootstrap/debugMode; then
    set -x
else
    exec &>> /tmp/pipe
fi


TEMPLATES_DIR="/templates"
WORKSPACE_DIR="/workspace"
ADDON="kube-state-metrics"
CONFIG_FILE="/etc/bootstrap/config"
VERSION="$(cat /etc/bootstrap/version)"
FROM_VERSION="$(cat /etc/bootstrap/from_version)"
K8S_VERSION="$(cat /tools/k8s_version)"

prepare_values() {
    # Create values.yaml in the workspace dir
    sed -e "s|^\(\s*repository: \)|\1$bds_k8s_containerrepo|g" $CONFIG_FILE > $WORKSPACE_DIR/values.yaml
}

# Utility functions to set error and initialize on the deployment configmap
set_deployment_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"initialize":"false","error":"false"}}'
}

set_deployment_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"initialize":"false","error":"true"}}'
}

clear_rollback() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"rollback":"false"}}'
}

set_reconfigure_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"reconfigure":"false","error":"false"}}'
}

set_reconfigure_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"reconfigure":"false","error":"true"}}'
}

set_upgrade_success() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"upgrade":"false","error":"false"}}'
}

set_upgrade_error() {
    kubectl patch configmap/hpecp-bootstrap-$ADDON --type merge -p '{"data":{"upgrade":"false","error":"true"}}'
}

# install related action for deploying the kube-state-metrics
# bdconfig (bds_XXX_YYY) variables are available as environnment variables
# /etc/bootstrap/config files are available through configmap
install() {
    echo "$(date): Starting kube-state-metrics install process"

    # copy from templates to workspace
    chmod 755 $WORKSPACE_DIR
    cp -a $TEMPLATES_DIR/* $WORKSPACE_DIR

    prepare_values

    echo "installing chart $ADDON"

    if ! helm install --namespace kube-system --values $WORKSPACE_DIR/values.yaml $ADDON $WORKSPACE_DIR/$ADDON; then
         echo "failed to install helm charts"
         set_deployment_error
         return 0
    fi

    set_deployment_success
    return 0
}

reconfigure() {
    echo "$(date): Starting kube-state-metrics reconfigure process"

    prepare_values

    if ! helm upgrade --namespace kube-system --values $WORKSPACE_DIR/values.yaml $ADDON $WORKSPACE_DIR/$ADDON; then
         echo "failed to upgrade helm chart"
         set_reconfigure_error
         return 0
    fi

    set_reconfigure_success
    return 0
}

# TEMPLATES_DIR will have the templates from new image and
# WORKSPACE_DIR will contain the existing modified ones.
# FROM_VERSION will contain the version that we are upgrading from
upgrade() {
    echo "$(date): Starting kube-state-metrics upgrade process"

    prepare_values

    if ! helm upgrade --namespace kube-system --values $WORKSPACE_DIR/values.yaml $ADDON $WORKSPACE_DIR/$ADDON; then
         echo "failed to upgrade helm chart"
         set_reconfigure_error
         return 0
    fi

    set_upgrade_success
    return 0
}

rollback() {
    echo "$(date): Starting kube-state-metrics rollback process"

    helm uninstall --namespace kube-system $ADDON

    clear_rollback
    return 0
}

if [ "$1" == "--install" ]
then
    install
elif [ "$1" == "--rollback" ]
then
    rollback
elif [ "$1" == "--reconfigure" ]
then
    reconfigure
elif [ "$1" == "--upgrade" ]
then
    upgrade
else
    echo "invalid argument"
fi
